export  const  AUTHENTICATION_LOADING = "AUTHENTICATION_LOADING";
export const  AUTHENTICATION_ERROR = "AUTH_ERROR";
// export  const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export  const LOGOUT = "LOGOUT";
export  const POST_SIGNUP_SUCCESS = "POST_SIGNUP_SUCCESS";
export  const CURRENT_USER = "CURRENT_USER";
export  const CURRENT_NAME = "CURRENT_NAME";